### ISSUE TITLE
recovery images for chromeOS versions?

### ISSUE THREAD

**Issue by justchen1369** [skylartaylor/cros-updates#11]
Recovery images seem to be missing for the boards, which some people may want to have. The download links to the recovery images seem to be in this format:
dl.google.com/dl/edgedl/chromeos/recovery/chromeos_`[build]`_`[board]`\_recovery\_`[channel]`-channel_mp.bin.zip

**Comment by skylartaylor** [comment]
I actually have the data for recovery for each device and channel, I just haven't figured out the best way to surface it. Do you have an opinion? I can't decide whether a separate recovery page or just integrating it into the current device page makes more sense.

**Comment by justchen1369** [comment]
I was thinking of something like this:
![mockup](https://user-images.githubusercontent.com/35386456/81209121-1483ad00-8f9e-11ea-8320-67ee6981540c.png)

**Comment by skylartaylor** [comment]
Something like this could totally work, my concern is that it'll end up having more visual weight on the page than the actual version data, which is what I anticipate most people will be coming for. 

I think most folks would use the recovery media tool rather than manually downloading an image. That said I still want to have it as a feature. UX is tough!

**Comment by skylartaylor** [comment]
this went live in https://github.com/skylartaylor/cros-updates/commit/d3e5208f3422fc2ae50a3f83fecf51d7a00c66a0 after a lot of work!
