### ISSUE TITLE
consider running the build scripts in heroku, and using an api to query the data from the client

### ISSUE THREAD

**Issue by justchen1369** [skylartaylor/cros-updates#13]
There are several potential benefits to putting the data from behind an api:

- (primary reason) This saves on Netlify build minutes as you no longer need to rebuild every 15 minutes, and only when you update the webapp.
- This eliminates the need to run a cronjob to update the data, as the heroku scheduler addon will do that.
  - assuming that the cronjob is on a personal computer, this will increase the reliability of the service in the event that something happens to personal internet or the computer.
- this will allow for a far less verbose commit history and reduce the overall size of it (given appropriate rewriting of the history, of course) 
 
I can think of several downsides:
- This will increase the complexity of the code, and would require that the data be validated in some way with a schema of some sort.
- This might take a fair bit of work to do.
- Given enough users, the heroku instance that the api endpoint is hosted on might be overloaded and require restructuring to reduce the load.
- you do lose out on git history, but as of right now no one's thought of a useful way to use it yet.

With your go-ahead, I'd like to conduct some experiments to check the feasibility the idea.

**Comment by skylartaylor** [comment]
My choice of Gatsby was very intentional. I wanted the site to be statically compiled for speed and for users who choose not to use javascript. 

I will eventually migrate the builds to github actions to save money, but in the mean time i am more than happy to spend my $14/mo for the website to be as performant and reliable as it is. 

This would be a very significant change to the project’s architecture, i’m not interested in pursuing it further.
