### ISSUE TITLE
Exposing /src/data/cros-updates.json

### ISSUE THREAD

**Issue by msnorman343** [skylartaylor/cros-updates#15]
Would you consider exposing the /src/data/cros-updates.json?  This would allow me to curl the json and develop a sense of update reporting.

**Comment by skylartaylor** [comment]
Hello! 

You can grab the JSON data from GitHub directly, since this repository is the source of truth! You can use the [Github](https://raw.githubusercontent.com/skylartaylor/cros-updates/master/src/data/cros-updates.json) link or [GitHack](https://raw.githack.com/skylartaylor/cros-updates/master/src/data/cros-updates.json) (A CDN that fixes some issues with text files from Github)
